import { StorageService } from './modules/storage/storage.service';
import { ProjectConfigService } from './modules/config/project-config.service';
import { ParserService } from './modules/parser/parser.service';
import { DriverFactoryService } from './modules/driver/driver-factory.service';
import { ComparatorService } from './modules/comparator/comparator.service';
import { SemanticDiffService } from './modules/comparator/semantic-diff.service';
import { MigratorService } from './modules/migrator/migrator.service';
import { ExporterService } from './modules/exporter/exporter.service';
import { SchemaMirrorService } from './modules/exporter/schema-mirror.service';
import { ReporterService } from './modules/reporter/reporter.service';
import { GitOrchestrator } from './modules/orchestration/git-orchestrator.service';
import { ImpactAnalysisService } from './modules/safety/impact-analysis.service';
import { SecurityOrchestrator } from './modules/orchestration/security-orchestrator.service';
import { SchemaOrchestrator } from './modules/orchestration/schema-orchestrator.service';
import { OrchestrationService } from './modules/orchestration/orchestration.service';
import { DependencySearchService } from './modules/search/dependency-search.service';
export declare class Container {
    private static instance;
    readonly storage: StorageService;
    readonly config: ProjectConfigService;
    readonly parser: ParserService;
    readonly driverFactory: DriverFactoryService;
    readonly comparator: ComparatorService;
    readonly semanticDiff: SemanticDiffService;
    readonly migrator: MigratorService;
    readonly exporter: ExporterService;
    readonly mirror: SchemaMirrorService;
    readonly reporter: ReporterService;
    readonly impactAnalysis: ImpactAnalysisService;
    readonly orchestrator: OrchestrationService;
    readonly dependencySearch: DependencySearchService;
    readonly gitOrchestrator: GitOrchestrator;
    readonly securityOrchestrator: SecurityOrchestrator;
    readonly schemaOrchestrator: SchemaOrchestrator;
    private constructor();
    static create(dbPath?: string): Container;
    static reset(): void;
    destroy(): void;
}
